- color: fef2c0
  description: Author 可申请锁住当前讨论
  name: Locked
- color: 22798A
  description: ""
  name: 区块链
- color: 7749E9
  description: ""
  name: 以太坊
- color: 306FB2
  description: ""
  name: Dapp
- color: 0CE712
  description: ""
  name: 货币
